// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAlert: typeof import('@arco-design/web-vue')['Alert']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACol: typeof import('@arco-design/web-vue')['Col']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AGrid: typeof import('@arco-design/web-vue')['Grid']
    AGridItem: typeof import('@arco-design/web-vue')['GridItem']
    AOption: typeof import('@arco-design/web-vue')['Option']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    MicroApp: typeof import('./src/components/MicroApp/index.vue')['default']
    ModalPluginStore: typeof import('./src/components/Modal/ModalPluginStore.vue')['default']
    ModalPluginStoreTitle: typeof import('./src/components/Modal/ModalPluginStoreTitle.vue')['default']
    ModalSettings: typeof import('./src/components/Modal/ModalSettings.vue')['default']
    PluginCard: typeof import('./src/components/Modal/sub/PluginCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchButton: typeof import('./src/components/Header/SearchButton.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar/index.vue')['default']
    SidebarButton: typeof import('./src/components/Sidebar/SidebarButton.vue')['default']
    SidebarButtonGroup: typeof import('./src/components/Sidebar/SidebarButtonGroup.vue')['default']
    ToolBar: typeof import('./src/components/Header/ToolBar.vue')['default']
    WindowController: typeof import('./src/components/Header/WindowController.vue')['default']
  }
}
