name: npm publish

on:
  push:
    branches:
      - main

jobs:

  publish:

    runs-on: windows-2022
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:

      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2

      - uses: actions/setup-node@v3.3.0
        with:
          node-version: '18.x'
          check-latest: true
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
          
      - name: install
        run: pnpm i
      - name: build
        run: pnpm build
      - name: release
        run: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}